### ISSUE TITLE
how do you use circular buffer for lidar values?

### ISSUE THREAD

**Issue by jeannotes** [5190GreenHopeRobotics/2018Bot#40]
Hi, i notice that you are using a circular buffer to handle lidar values, can you share some ideas for implementing this?

**Comment by prateekma** [comment]
https://github.com/5190GreenHopeRobotics/2018CompetitionSeason/blob/master/src/main/kotlin/frc/team5190/robot/util/CircularBuffer.kt

We use the circular buffer to store a rolling average of the Lidar sensor value instead of using a single value.

**Comment by jeannotes** [comment]
@prateekma so, this is actually a list array, a simplified circular buffer?

**Comment by prateekma** [comment]
Yes, it uses ArrayLists with added functionality for the rolling average
